apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gateway
  labels:
    {{- include "consulting-pm.labels" . | nindent 4 }}
spec:
  selector:
    app: gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: {{ .Values.gateway.service.port }}
