apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: consulting-pm-dev

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: dev

images:
  - name: consulting-pm/gateway
    newTag: dev
  - name: consulting-pm/auth
    newTag: dev
  - name: consulting-pm/projects
    newTag: dev
  - name: consulting-pm/timelog
    newTag: dev
  - name: consulting-pm/billing
    newTag: dev
  - name: consulting-pm/resources
    newTag: dev
  - name: consulting-pm/notifications
    newTag: dev

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: HorizontalPodAutoscaler
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 2
  - target:
      kind: PodDisruptionBudget
    patch: |-
      - op: replace
        path: /spec/minAvailable
        value: 0
  - target:
      kind: Deployment
      name: ".*"
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 50m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 64Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 250m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 256Mi
